kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        protocol: TCP
      - containerPort: 30003
        hostPort: 443
        protocol: TCP
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            # Como seu host tem 10 CPUs e 20GB, reservamos o excesso
            # para que o K8s gerencie apenas 2 CPUs e 4GB para seus Pods
            kube-reserved: "cpu=7,memory=15Gi"
            system-reserved: "cpu=1,memory=1Gi"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            kube-reserved: "cpu=7,memory=15Gi"
            system-reserved: "cpu=1,memory=1Gi"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            kube-reserved: "cpu=7,memory=15Gi"
            system-reserved: "cpu=1,memory=1Gi"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=platform"