kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        protocol: TCP
      - containerPort: 30003
        hostPort: 443
        protocol: TCP
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=application"
            kube-reserved: "cpu=7,memory=15Gi"
            system-reserved: "cpu=1,memory=1Gi"
          taints:
            - key: "dedicated"
              value: "application"
              effect: "NoSchedule"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=application"
            kube-reserved: "cpu=7,memory=15Gi"
            system-reserved: "cpu=1,memory=1Gi"
          taints:
            - key: "dedicated"
              value: "application"
              effect: "NoSchedule"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=application"
            kube-reserved: "cpu=7,memory=15Gi"
            system-reserved: "cpu=1,memory=1Gi"
          taints:
            - key: "dedicated"
              value: "application"
              effect: "NoSchedule"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload=platform,istio-injection=enabled"