apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-gen-node-hpa
  namespace: hands-on-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-gen-node
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
